[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cairo",
  "pango",
  "glib",
  "gtk3",
  "dbus",
  "cups",
  "libdrm",
  "libxkbcommon",
  "alsa-lib",
  "mesa",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libXtst"
]
